create table company_update_history
(
    id         bigint generated by default as identity
        constraint company_update_history_pk
            primary key,
    history    date,
    created_at timestamp,
    updated_at timestamp
);