create table if not exists company
(
    id                  bigint generated by default as identity
        primary key,
    created_at          timestamp,
    updated_at          timestamp,
    fax_number          varchar(255),
    keyword             varchar(255),
    location            varchar(255),
    name                varchar(255),
    phone_number        varchar(255),
    scale               varchar(255),
    sector              varchar(255),
    government_location varchar(255),
    kreditjob_key       varchar(255),
    service_type        varchar(255)
);

create index if not exists idxniu8sfil2gxywcru9ah3r4ec5
    on company (name);

